# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_macpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macpost',
            name='mac_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='macpost',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
