# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_memnuniyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memnuniyet',
            name='gelen_tarih',
            field=models.CharField(max_length=30),
        ),
    ]
