# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_auto_20180426_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='memnuniyet',
            name='tipi',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
